### PR TITLE
Add option to strip history when writing features

### PR DESCRIPTION
**Pull request by xylar**
This is needed in split_features.py to prevent modifying features
by combining and splitting them, and to prevent potentially
sensitive data included in provenance from being stored in a public
repository.

Also, a little bit of suggested clean up.

### CODE REVIEW

**Comment by xylar** [comment]
@pwolfram, these changes are meant to address my concerns about the provenance PR you made months and months ago.

Assuming you're okay with this, I'd suggest merging these changes (or just cherry-picking them from my branch) and then rebasing onto `master`, since there are some conflicts.  If you have trouble with the rebase, no worries.  I did a test merge and was able to fix the conflicts, and I can do the same for the "real" merge.

After my test merge, a did
```
./merge_features.py -d ocean/region/
vim features.geojson 
./split_features.py -f features.geojson 
```
I was able to confirm that the expected history option exists in each feature in `features.geojson` and that resplitting left the features unchanged.  Note that the same was not true *before* my test merge, so rebasing onto `master` will be important.

**Comment by pwolfram** [comment]
@xylar, do you want to do the rebase here so that you can get clean credit for this PR?  I'd like to get this merged in today if possible so we can get it off the queue.  Thanks!

**Comment by xylar** [comment]
Yep, I can do that.  Meaning I just update your branch rather than having us commit this PR to your branch?

**Comment by xylar** [comment]
I see, you just wanted me to rebase and clean up the conflicts.  I'll push in just a second.

**Comment by xylar** [comment]
At this point, I'm not sure what the best way is of merging this branch.  You might just need to reset --hard to this commit and then close this PR.

**Comment by pwolfram** [comment]
Ok, I *think* I got all your changes.  Can you please checkout my branch to make sure and compare against your changes?  If you are ok with the changes we can probably close this PR and just move on to https://github.com/MPAS-Dev/geometric_features/pull/64 to fully resolve.

**Pull request closed without merging**
